default:
  image: ghcr.io/prefix-dev/pixi:latest
  before_script:
    - pixi install

stages:
  - test
  - build
  - release

test_job:
  stage: test
  script:
    - pixi run lint
    - pixi run typecheck
    - pixi run test

build_job:
  stage: build
  script:
    - pixi run python -m build
  artifacts:
    paths:
      - dist/

pages:
  stage: release
  only:
    - tags
  script:
    - mkdir public
    - cd docs/
    - pixi run sphinx-apidoc --private --force -d 0 --no-headings --module-first --no-toc -o API/ ../pyfastspm
    - pixi run sphinx-build -b html -d _build/doctrees . _build/html
    - mv -v _build/html/* ../public/
  artifacts:
    paths:
      - public
