workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

default:
  image: ghcr.io/prefix-dev/pixi:latest
  before_script:
    - pixi install

stages:
  - test
  - build
  - release

test_job:
  stage: test
  script:
    - pixi run lint
    - pixi run test
    - pixi run test_notebook

build_job:
  stage: build
  script:
    - pixi run build_pypi
  artifacts:
    paths:
      - dist/

release_pypi:
  stage: release
  only:
    - tags
  script:
    - pixi run publish_pypi

pages:
  stage: release
  only:
    - tags
  script:
    - mkdir public
    - cd docs/
    - pixi run sphinx-apidoc --private --force -d 0 --no-headings --module-first
      --no-toc -o API/ ../pyfastspm
    - pixi run sphinx-build -b html -d _build/doctrees . _build/html
    - mv -v _build/html/* ../public/
  artifacts:
    paths:
      - public
